url: https://indidem.github.io
baseurl: /

# Site settings
title: Shirley Bongers' Family History
email: indidem@gmail.com
description: "This website provides access to Shirley Bongers' family history research."

# Team
people:
- name: Shirley
  pic: team-1
  position: Emeritus Researcher Extraordinaire

- name: Allison
  pic: team-2
  position: Editor in Chief, analyst & archivist

- name: Jessica
  pic: team-3
  position: Designer, analyst, developer & archivist

# Social
social:
  - title: github
    url: http://github.com/indidem 

# Build settings
markdown: kramdown
permalink: pretty
